version: '3.8'

services:
  # Firebase Emulators
  firebase-emulators:
    image: andreysenov/firebase-tools
    ports:
      - "4000:4000"  # Emulator UI
      - "5001:5001"  # Functions
      - "8080:8080"  # Firestore
      - "9199:9199"  # Storage
    volumes:
      - ./backend:/app
    working_dir: /app
    command: firebase emulators:start

  # Mobile Development
  app-dev:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - "19000:19000"  # Expo
      - "19001:19001"  # Expo DevTools
      - "19002:19002"  # Expo Web
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - firebase-emulators

  # Backend Development
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"  # API
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FIREBASE_EMULATOR=true
    depends_on:
      - firebase-emulators 